### ISSUE TITLE
Questions about this repo

### ISSUE THREAD

**Issue by oferb** [hasadna/datacity-businessgate#1]
Hey,
Looks like this repo contains compiled code for the [asakim.datacity.org.il](https://asakim.datacity.org.il) chatbot, as part of the DataCity project:
![image](https://user-images.githubusercontent.com/5137671/100583321-33a7aa80-32f3-11eb-86ed-1a3d55ab6dfb.png)
There have been several pushes to this repo (about 5 this month), such that every push deletes the previous commits history.

Let me know if my understanding is incorrect.

1. Is the open source code published by Hasadna?
2. In general, does Hasadna do closed-sourced development in the DataCity project?

Thanks!

**Comment by RoySegall** [comment]
> Is the open source code published by Hasadna?

As far as I can see, the repo which contains source code is private. Don't know why.

> In general, does Hasadna do closed-sourced development in the DataCity project?

@akariv ^^

**Comment by akariv** [comment]
This is a utility repo used for publishing the website using github pages.

The development is done in a private repo atm because it contains data from the BeerSheva municipality which wasn't cleared for publication by their legal department.

Of course that when it will be approved it will be changed to public. In case it doesn't, we would separate the code and the data to different repos and leave just the data private.

All of this will happen in the upcoming month (this way or another).

@oferb @roysegall ^^^

**Comment by oferb** [comment]
Thanks for the prompt response!

Maybe you can use `.gitignore` to ignore the files with the private data?

**Comment by RoySegall** [comment]
Why not a submodule 🤷‍♂️ ?

**Comment by akariv** [comment]
.gitignore is too prone to errors I think, esp. since we're dealing here
with (potentially) private data.
submodule might be a good option for the final architecture in case it's
decided not to publish some or all the data.
